[package]
name = "expansion_pack"
edition = "2024"

[dependencies]
monban = { git = "https://github.com/blockchainBard101/monban.git", rev = "testnet/v1" }
game_core = { local = "../game_core" }

[addresses]
expansion_pack = "0x0"
